In [32]:
import numpy as np

text = """
                                        NumPy: DASAR - DASAR MUTLAK UNTUK PEMULA

NumPy (Python Numerik) adalah pustaka Python sumber terbuka yang digunakan di hampir semua bidang ilmu pengetahuan dan teknik. 
NumPy adalah standar universal untuk bekerja dengan data numerik dalam Python, dan merupakan inti dari ekosistem Python
ilmiah dan PyData. Pengguna NumPy mencakup semua orang, mulai dari pembuat kode pemula hingga peneliti berpengalaman yang 
melakukan penelitian dan pengembangan ilmiah dan industri pertukaran. API NumPy digunakan secara luas di Panda, SciPy,
Matplotlib, scikit-learn, scikit-image, dan sebagian besar paket Python sains dan ilmiah lainnya.

Perpustakaan NumPy berisi struktur data larik multidimensi dan matriks (Anda akan menemukan lebih banyak informasi mengenai 
hal ini di bagian selanjutnya). NumPy menyediakan ndarray, sebuah objek larik n-dimensi yang homogen, dengan metode-metode 
untuk mengoperasikannya secara efisien. NumPy dapat digunakan untuk melakukan berbagai macam operasi matematika pada larik. 
NumPy menambahkan struktur data yang kuat ke dalam Python yang menjamin perhitungan yang efisien dengan larik dan matriks, 
serta menyediakan pustaka fungsi matematika tingkat tinggi yang sangat banyak yang beroperasi pada larik dan matriks.

                                                Menginstal NumPy

Untuk menginstal NumPy, kami sangat menyarankan untuk menggunakan distribusi Python ilmiah. Jika Anda mencari petunjuk 
lengkap untuk menginstal NumPy pada sistem operasi Anda, lihat Menginstal NumPy.

Jika Anda sudah memiliki Python, Anda dapat menginstal NumPy dengan :
conda instal numpy
atau
pip instal numpy

Jika Anda belum memiliki Python, Anda mungkin ingin mempertimbangkan untuk menggunakan Anaconda. Ini adalah cara 
termudah untuk memulai. Hal yang baik tentang mendapatkan distribusi ini adalah kenyataan bahwa Anda tidak perlu 
terlalu khawatir tentang menginstal NumPy secara terpisah atau paket-paket utama yang akan Anda gunakan untuk analisis 
data Anda, seperti pandas, Scikit-Learn, dll.

                                                Cara mengimpor NumPy

Untuk mengakses NumPy dan fungsi-fungsinya, imporlah ke dalam kode Python Anda seperti ini:
# import numpy sebagai np

Kami mempersingkat nama yang diimpor menjadi np untuk keterbacaan kode yang lebih baik dengan menggunakan NumPy. Ini 
adalah konvensi yang diadopsi secara luas yang membuat kode Anda lebih mudah dibaca oleh semua orang yang mengerjakannya. 
Kami merekomendasikan untuk selalu menggunakan impor numpy sebagai np.

"""
print(text)


                                        NumPy: DASAR - DASAR MUTLAK UNTUK PEMULA

NumPy (Python Numerik) adalah pustaka Python sumber terbuka yang digunakan di hampir semua bidang ilmu pengetahuan dan teknik. 
NumPy adalah standar universal untuk bekerja dengan data numerik dalam Python, dan merupakan inti dari ekosistem Python
ilmiah dan PyData. Pengguna NumPy mencakup semua orang, mulai dari pembuat kode pemula hingga peneliti berpengalaman yang 
melakukan penelitian dan pengembangan ilmiah dan industri pertukaran. API NumPy digunakan secara luas di Panda, SciPy,
Matplotlib, scikit-learn, scikit-image, dan sebagian besar paket Python sains dan ilmiah lainnya.

Perpustakaan NumPy berisi struktur data larik multidimensi dan matriks (Anda akan menemukan lebih banyak informasi mengenai 
hal ini di bagian selanjutnya). NumPy menyediakan ndarray, sebuah objek larik n-dimensi yang homogen, dengan metode-metode 
untuk mengoperasikannya secara efisien. NumPy dapat digunakan untuk melakukan b

In [41]:
import numpy as np

#Membaca contoh kode
a = np.arange(6) 
a2 = a[np.newaxis, :]
print(a2.shape)

#Apa yang dimaksud dengan array ?
a = np.array([1, 2, 3, 4, 5, 6])
#atau
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

#Apa saja atribut dari sebuah larik ?
A = np.array([[0., 0., 0.],
              [1., 1., 1.]])
print("Matriks A:")
print(A)

text = """
                                    Cara membuat larik dasar

Bagian ini mencakup np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype. 
Untuk membuat larik NumPy, Anda dapat menggunakan fungsi np.array()                           
"""
print(text)

import numpy as np
B = np.array([1, 2, 3])
print("Matriks B:")
print(B)

zeros_array = np.zeros(2)
print("larik yang berisi angka 0 : ")
print(zeros_array)

ones_array = np.ones(2)
print("larik yang diisi dengan angka 1 :")
print(ones_array)

# Membuat larik kosong dengan 2 elemen
empty_array = np.empty(2)
print("Membuat larik kosong dengan 2 elemen")
print(empty_array)

array = np.arange(4)
print("Anda dapat membuat larik dengan sejumlah elemen : ")
print(array)

arr = np.arange(2, 9, 2)
print("menentukan angka pertama, angka terakhir, dan ukuran langkah")
print(arr)

arr = np.linspace(0, 10, num=5)
print("menggunakan np.linspace()")
print(arr)

x = np.ones(2, dtype = np.int64)
print("Menentukan tipe data Anda")
print(x)

text = """
                                    Menambahkan, menghapus, dan menyortir elemen

Bagian ini mencakup np.sort(), np.concatenate().

Mengurutkan elemen sangat mudah dengan np.sort(). Anda dapat menentukan sumbu, jenis, dan urutan ketika Anda memanggil fungsi tersebut.
Jika Anda memulai dengan array ini:
"""
print(text)

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print("mengurutkan angka dalam urutan menaik dengan")
print(np.sort(arr))

text = """
Selain mengurutkan, yang mengembalikan salinan larik yang diurutkan, Anda dapat
menggunakan:
1. argsort, yang merupakan pengurutan tidak langsung di sepanjang sumbu tertentu,
2. lexsort, yang merupakan pengurutan stabil tidak langsung pada beberapa tombol,
3. Pencarian terurut, yang akan menemukan elemen dalam larik terurut, dan
4. partisi, yang merupakan pengurutan parsial.

mengurutkan larik, lihat: mengurutkan. Jika
Anda memulai dengan larik ini:
"""
print(text)

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("menggabungkannya dengan np.concatenate().")
print(np.concatenate((a, b)))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print("memulai dengan susunan ini :")
print(np.concatenate((x, y), axis=0))

text = """
                                        Bagaimana Anda mengetahui bentuk dan ukuran array?

Bagian ini mencakup ndarray.ndim, ndarray.size, ndarray.shape.

ndarray.ndim akan memberi tahu Anda jumlah sumbu, atau dimensi, dari larik.

ndarray.size akan memberi tahu Anda jumlah total elemen larik. Ini adalah hasil kali dari elemen-elemen bentuk larik.

ndarray.shape akan menampilkan sebuah tupel bilangan bulat yang menunjukkan jumlah elemen yang disimpan di setiap dimensi larik. Misalnya, 
jika Anda memiliki larik 2-D dengan 2 baris dan 3 kolom, bentuk larik Anda adalah (2, 3). Contohnya, jika Anda membuat larik ini:
"""
print(text)

array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print("Untuk menemukan jumlah dimensi array, jalankan:")
print(array_example.ndim)
print("Untuk menemukan jumlah total elemen dalam larik, jalankan:")
print(array_example.size)
print("Dan untuk menemukan bentuk array Anda, jalankan:")
print(array_example.shape)

text = """ 
                                        Dapatkah Anda membentuk ulang sebuah larik?

Bagian ini mencakup arr.reshape().

Menggunakan arr.reshape() akan memberikan bentuk baru pada larik tanpa
mengubah datanya. Ingatlah bahwa ketika Anda menggunakan metode reshape, larik yang
ingin Anda buat harus memiliki jumlah elemen yang sama dengan larik aslinya. Jika Anda
memulai dengan larik dengan 12 elemen, Anda harus memastikan bahwa larik baru Anda
juga memiliki total 12 elemen.
Jika Anda memulai dengan array ini:
"""
print(text)

a = np.arange(6)
print(a)

print("Anda dapat menggunakan reshape() untuk membentuk ulang larik Anda. Sebagai contoh, Anda dapat membentuk ulang larik ini menjadi larik dengan tiga baris dan dua kolom:")

b = a.reshape(3, 2)
print(b)

print("Dengan np.reshape, Anda dapat menentukan beberapa parameter opsional:")
print(np.reshape(a, newshape = (1, 6), order = 'C'))

print("Cara mengonversi larik 1D menjadi larik 2D (cara menambahkan sumbu baru ke larik)")
a = np.array([1, 2, 3, 4, 5, 6])
print(a. shape)

print("menggunakan np.newaxis untuk menambahkan sumbu baru:")
a2 = a[np.newaxis, :]
print(a2.shape)

print("menyisipkan sumbu di sepanjang dimensi pertama:")
row_vector = a[np.newaxis, :]
print(row_vector.shape)

print("untuk vektor kolom, Anda dapat menyisipkan sumbu di sepanjang dimensi kedua:")
col_vector = a[:, np.newaxis]
print(col_vector.shape)

print("Anda juga dapat memperluas larik dengan menyisipkan sumbu baru pada posisi tertentu dengan np.expand_dims.")
a = np.array([1, 2, 3, 4, 5, 6])
print(a. shape)

print("menggunakan np.expand_dims untuk menambahkan sumbu pada posisi indeks 1 dengan:")
b = np.expand_dims(a, axis=1)
print(b. shape)

print(" menambahkan sumbu pada posisi indeks 0 dengan:")
c = np.expand_dims(a, axis=0)
print(c. shape)

print("Mengindeks dan mengiris")
data = np.array([1, 2, 3])
print(data [1])
print(data [0:2])
print(data[1:])
print(data[-2:])

print("Contohnya, jika Anda memulai dengan array ini:")
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

print("menggunakan kondisi tersebut untuk mengindeks larik")
five_up = (a >= 5)
print(a[five_up])

print("Anda dapat memilih elemen yang dapat dibagi 2:")
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

print("menggunakan operator & dan | :")
c = a[(a > 2) & (a < 11)]
print(c)

print("berguna pada larik yang berisi nama atau nilai kategorikal lainnya")
five_up = (a > 5) | (a == 5)
print(five_up)

print("menggunakan np.nonzero() untuk memilih elemen atau indeks dari larik")
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

print(a[b])

not_there = np.nonzero(a == 42)
print(not_there)

(1, 6)
[1 2 3 4]
Matriks A:
[[0. 0. 0.]
 [1. 1. 1.]]

                                    Cara membuat larik dasar

Bagian ini mencakup np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype. 
Untuk membuat larik NumPy, Anda dapat menggunakan fungsi np.array()                           

Matriks B:
[1 2 3]
larik yang berisi angka 0 : 
[0. 0.]
larik yang diisi dengan angka 1 :
[1. 1.]
Membuat larik kosong dengan 2 elemen
[1. 1.]
Anda dapat membuat larik dengan sejumlah elemen : 
[0 1 2 3]
menentukan angka pertama, angka terakhir, dan ukuran langkah
[2 4 6 8]
menggunakan np.linspace()
[ 0.   2.5  5.   7.5 10. ]
Menentukan tipe data Anda
[1 1]

                                    Menambahkan, menghapus, dan menyortir elemen

Bagian ini mencakup np.sort(), np.concatenate().

Mengurutkan elemen sangat mudah dengan np.sort(). Anda dapat menentukan sumbu, jenis, dan urutan ketika Anda memanggil fungsi tersebut.
Jika Anda memulai dengan array ini:

mengurutkan angka d

In [142]:
import numpy as np

# Cara membuat larik dari data yang sudah ada
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = a[3:8]
print(arr1)

a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])
print("Anda memiliki dua larik, a1 dan a2:")

print("Anda dapat menumpuknya secara vertikal dengan vstack:")
print(np.vstack((a1, a2)))

print("Atau susun secara horizontal dengan hstack:")
print(np.hstack((a1, a2)))

x = np.arange(1, 25).reshape(2, 12)
print("Katakanlah Anda memiliki susunan ini:")
print(x)

print("membagi larik ini menjadi tiga larik dengan bentuk yang sama")
print(np.hsplit(x, 3))

print("membagi larik Anda setelah kolom ketiga dan keempat")
print(np.hsplit(x, (3, 4)))

print("metode view untuk membuat objek larik baru yang melihat data yang sama dengan larik asli (salinan dangkal).")
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
b1 = a[0, :]
print("membuat larik b1 dengan mengiris a dan memodifikasi elemen pertama dari b1")
print(b1)
b1[0] = 99
print(b1)
print(a)

print(" metode salin akan membuat salinan lengkap larik dan datanya (salinan dalam)")
b2 = a.copy()
print(b2)

print("Operasi larik dasar")
data = np.array([1,2])
ones = np.ones(2, dtype = int)
print(data + ones)

print("melakukan lebih dari sekadar penambahan!")
print(data - ones)
print(data * data)
print(data / data)

print("larik 1D, larik 2D, dan larik dengan dimensi yang lebih tinggi.")
a = np.array([1, 2, 3, 4])
print(a.sum())

print("menambahkan baris atau kolom dalam larik 2D, Anda akan menentukan sumbu.")
b = np.array([[1, 1], [2, 2]])
print("menjumlahkan di atas sumbu baris dengan:")
print(b.sum(axis=0))
print("menjumlahkan di atas sumbu kolom dengan:")
print(b.sum(axis=1))

print("PENYIARAN")
data = np.array([1.0, 2.0])
print(data * 1.6)

print("OPERASI LARIK YANG LEBIH BERGUNA")
print(data.max())
print(data.min())
print(data.sum())

print("mulai dengan larik ini, yang disebut a")
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print("menemukan jumlah atau minimum dari elemen-elemen dalam larik")
print(a.sum())
print("Atau :")
print(a.min())

print("menemukan nilai minimum dalam setiap kolom dengan menentukan sumbu=0")
print(a.min(axis=0))

print("MEMBUAT MATRIKS")
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

print("Operasi pengindeksan dan pemotongan berguna saat Anda memanipulasi matriks:")
print(data[0, 1])
print(data [1:3])
print(data [0:2, 0])

print("menggabungkan matriks dengan cara yang sama seperti menggabungkan vektor:")
print(data.max())
print(data.min())
print(data.sum())

print("kumpulan data yang sedikit dimodifikasi:")
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

print("operator aritmatika memiliki dua matriks dengan ukuran yang sama")
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print(data + ones)

print("menggunakan aturan broadcast untuk melakukan operasi")
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print(data + ones_row)

print("array N-dimensi, sumbu terakhir akan dilingkari paling cepat sementara sumbu pertama adalah yang paling lambat")
print(np.ones((4, 3, 2)))

print("fungsi seperti ones() dan zeros(), dan kelas random.Generator untuk menghasilkan angka acak")
print(np.ones(3))
print(np.zeros(3))
rng = np.random.default_rng()
random_numbers = rng.random(3)
print(random_numbers)

print("menggunakan ones(), zeros(), dan random() untuk membuat larik 2D")
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(rng.random((3, 2)))

print("MENGHASILKAN ANGKA ACAK")
print("membuat larik 2 x 4 bilangan bulat acak antara 0 dan 4 dengan:")
print(rng.integers(5, size=(2, 4)))

print("CARA MENDAPATKAN ITEM DAN JUMLAH UNIK")
a = np.array([11, 11, 12, 13, 14, 14, 15, 16, 17, 12, 13, 11, 14, 18,
19, 20])
nilai_unik = np.unique(a)
print(nilai_unik)

print("argumen return_index dalam np.unique().")
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

print("argumen return_counts di np.unique().")
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

print("dengan array 2D! Jika Anda memulai dengan array ini:")
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1,
2, 3, 4]])
print("dapat menemukan nilai unik dengan :")
nilai_unik = np.unique(a_2d)
print(nilai_unik)

print("baris unik,tentukan axis = 0 dan untuk kolom,tentukan axis = 1.")
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

print("mendapatkan baris unik, posisi indeks, dan jumlah kemunculan")
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

print("MENGUBAH DAN MEMBENTUK ULANG MATRIKS")
print("*metode reshape")
print(data.reshape(2, 3))
print(data.reshape(3, 2))

print("* menggunakan .transpose()")
arr = np.arange(6).reshape((2, 3))
print(arr)

print("*transposisi larik dengan arr.transpose()")
print(arr.transpose())

print("*menggunakan arr.T:")
print(arr.T)

print("CARA MEMBALIKKAN LARIK")
print("Membalikkan larik 1D")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("*membalikkan dengan :")
reversed_arr = np.flip(arr)
print(arr)
print("*mencetak larik terbalik :")
print('Reversed Array: ', reversed_arr)

print("Membalikkan larik 2D")
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("*membalikkan konten di semua baris dan semua kolom :")
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

print("*membalikkan hanya baris :")
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

print("*membalikkan hanya kolom :")
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

print("*membalikkan isi baris pada posisi indeks 1 (baris kedua):")
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

print("*membalikkan kolom pada posisi indeks 1 (kolom kedua):")
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

print("MEMBENTUK ULANG DAN MERATAKAN SUSUNAN MULTIDIMENSI")
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("*menggunakan flatten untuk meratakan larik Anda menjadi larik 1D")
print(x.flatten())

print("*perubahan pada larik baru Anda tidak akan mengubah larik induk")
a1 = x.flatten()
a1[0] = 99
print(x)
print(a1)

print("*perubahan yang Anda buat pada larik baru akan mempengaruhi larik induk.")
a2 = x.ravel()
a2[0] = 98
print(x)
print(a2)

print("CARA MENGAKSES DOCSTRING UNTUK INFORMASI LEBIH LANJUT")













[4 5 6 7 8]
Anda memiliki dua larik, a1 dan a2:
Anda dapat menumpuknya secara vertikal dengan vstack:
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
Atau susun secara horizontal dengan hstack:
[[1 1 3 3]
 [2 2 4 4]]
Katakanlah Anda memiliki susunan ini:
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
membagi larik ini menjadi tiga larik dengan bentuk yang sama
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
membagi larik Anda setelah kolom ketiga dan keempat
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]
metode view untuk membuat objek larik baru yang melihat data yang sama dengan larik asli (salinan dangkal).
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
membuat larik b1 dengan mengiris a dan memodifikasi elemen pertama dari b1
[1 2 3 4]
[99  2  3  4]
[[99 